name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: false

      - name: Prerequisites
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: CommonInstall
        run: pnpm install

      - name: EngineInstall
        run: cd engine && pnpm install

      - name: EngineBuild
        run: NODE_ENV=production cd engine && pnpm run build

      - name: GameInstall
        run: cd game && pnpm install

      - name: GameBuild
        run: cd game && pnpm run build -- --production

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: game/www
          cname: pixelheart.io
