name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: false

      - name: Prerequisites
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install
        run: pnpm install

      - name: GameInstall
        run: cd game && pnpm install

      - name: Build
        run: pnpm run dist:build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: www
          cname: pixelheart.io
