name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: false

      - name: Prerequisites
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Installing common packages
        run: pnpm install

      - name: Installing engine packages
        run: cd engine && pnpm install

      - name: Building engine
        run: NODE_ENV=production cd engine && pnpm run build

      - name: Installing game packages
        run: cd game && pnpm install

      - name: Building game
        run: cd game && pnpm run build --production

      - name: Deploying game to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: game/www
          cname: pixelheart.io
